# Generated by Django 2.2.6 on 2020-04-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_infected', models.IntegerField()),
                ('number_of_death', models.IntegerField()),
                ('number_of_survive', models.IntegerField()),
            ],
        ),
    ]
